- find_compilers_packages.py
- packages.yaml
Previous fix (#2) didn't work as the code for find `mkl` has a very strict idea of where the library should be.
This fix tries to use a more standard location path.
Closes #1
> Try again to fix mkl paths

- v0.20/ci/modules.yaml
- v0.20/common/modules.yaml
- v0.20/gadi/modules.yaml
```
$ spack config get modules
modules:
default:
enable:
- tcl
roots:
tcl: $spack/../release/modules
lmod: $spack/../release/lmod
tcl:
hash_length: 0
exclude_implicits: true
include:
- access-om2
- mom5
- cice5
- libaccessom2
- oasis3-mct
all:
autoload: direct
conflict:
- '{name}'
environment:
set:
SPACK_{name}_ROOT: '{prefix}'
projections:
all: '{name}/{version}'
lmod:
all:
autoload: direct
hierarchy:
- mpi
prefix_inspections:
./bin:
- PATH
./man:
- MANPATH
./share/man:
- MANPATH
./share/aclocal:
- ACLOCAL_PATH
./lib/pkgconfig:
- PKG_CONFIG_PATH
./lib64/pkgconfig:
- PKG_CONFIG_PATH
./share/pkgconfig:
- PKG_CONFIG_PATH
./:
- CMAKE_PREFIX_PATH
```
```
$ spack install access-om2 ^netcdf-c@4.7.4 ^netcdf-fortran@4.5.2 ^nci-openmpi@4.0.2 %intel@19.0.5.281
$ module avail
--------- …
```
> Add modulefile support

- .github/workflows/update-deployment-repos.yml
This enforces sign off before modifying the deployment target.
> update-deployment-repos: Now uses a deployment environment

- spack-start.bash
* Since this script is dot sourced into the user's environment, we shouldn't set any temporary variables.
> spack-start.bash: do not set unnecessary variables

- v0.20/ci/packages.yaml
The Spack config for gadi already pins CMake to version 3.24.2. See `v0.20/gadi/packages.yaml`:
```
packages:
...
cmake:
externals:
- spec: cmake@3.24.2
prefix: /apps/cmake/3.24.2
buildable: false
```
We should do the same in the Spack config for CI.
> Pin cmake to 3.24.2 for CI

- v0.20/ci/packages.yaml
The Spack config for gadi already uses system perl. See v0.20/gadi/packages.yaml. We should do the same in the Spack config for CI.
> v0.20/ci/packages.yaml: use system perl

- common/gadi/packages.yaml
* This commit requires https://github.com/ACCESS-NRI/spack-packages/pull/66 for ACCESS-OM2 to build on Gadi.
> common/gadi/packages.yaml: use system openmpi directly

- common/ci/packages.yaml
* In Spack v0.21, libevent-2.1.12 complains:
libtool: Version mismatch error.  This is libtool 2.4.7, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.42-b88ce-dirty.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
> common/ci/packages.yaml: pin libtool to version 2.4.6 or less

- common/gadi/linux/compilers.yaml
1) for i in $(module avail -t intel-compiler/ intel-compiler-llvm/ | grep ^intel-compiler | tr '\n' ' '); do echo "= $i ="; module load $i; spack compiler find; module unload $i ; done 2>&1 | tee ~/spack.yaml.log
2) Copy the module name into the yaml file's modules list variable.
> common/gadi/linux/compilers.yaml: add all the intel-compilers on Gadi

- common/ci/packages.yaml
* CMake 3.24.2 is deprecated in Spack v0.22.
> common/ci/packages.yaml: require CMake 3.24.4

- v0.21/gadi/packages.yaml
Closes #33 . Tested by appending
```
depends_on("hdf5@1.14.3")
```
to
```
with when("@access-esm1.5"):
depends_on("oasis3-mct@access-esm1.5")
```
in https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/mom5/package.py . Running
```
$ spack install mom5@access-esm1.5%intel@19.0.5.281 arch=linux-rocky8-x86_64
```
then results in
```
==> Error: concretization failed for the following reasons:
1. FPE bug in hdf5@1.14.3 is not patched in Spack versions earlier than v0.22
```
> Avoid using HDF5 version 1.14.3

- common/gadi/linux/compilers.yaml
* The dpcpp compiler has been removed from Spack v0.22: https://github.com/spack/spack/pull/43418
> gadi/linux/compilers.yaml: remove dpcpp compiler

- common/modules.yaml
* The ACCESS-OM2 environment's spack.yaml will contain the include list.
> common/modules.yaml: remove ACCESS-OM2 specific include list

- common/config.yaml
Overriding `environments_root` and `source_cache` to point outside of the `spack` git repository takes us one step closer to an immutable spack directory. Thanks @atteggiani for prompting me to look at this.
> common/config.yaml: override environments_root and source_cache

- common/gadi/linux/compilers.yaml
It's possible that a user might want to use our Spack instance on Gadi with a newer GCC compiler. Hopefully, this can avoid a help request.
> common/gadi/linux/compilers.yaml: add all the gcc compilers on Gadi

- common/gadi/packages.yaml
Set $CMAKE_PREFIX_PATH to workaround Gadi's openmpi directory layout. This means MPI compiler wrappers being explicitly passed to CMake are not required in SPDs, anymore.
Without this change, the upstream Spack's FMS package will not build: https://github.com/spack/spack/issues/45358
> common/gadi/packages.yaml: add extra_attributes to openmpi spec

- common/gadi/packages.yaml
* Thanks to Paul Leopardi for finding $NCI_PYTHONX_AS_PYTHON.
* Sort into alphabetical order.
> common/gadi/packages.yaml: add Python as an external

- common/gadi/linux/compilers.yaml
FMS only compiles correctly with the latest version of the Intel OneAPI compilers available on gadi.
> Add latest version of the Intel OneAPI compilers on gadi

- common/gadi/linux/compilers.yaml
The 2025 oneAPI is now available on `gadi`
> Added oneAPI 2025 compiler

- common/ci-runner/upstreams.yaml
- common/ci-upstream/config.yaml
- common/ci-upstream/modules.yaml
- v0.22/ci-runner/concretizer.yaml
- v0.22/ci-runner/config.yaml
- v0.22/ci-runner/modules.yaml
- v0.22/ci-runner/packages.yaml
- v0.22/ci-runner/repos.yaml
- v0.22/ci-runner/upstreams.yaml
- v0.22/ci-upstream/concretizer.yaml
- v0.22/ci-upstream/config.yaml
- v0.22/ci-upstream/modules.yaml
- v0.22/ci-upstream/packages.yaml
- v0.22/ci-upstream/repos.yaml
References ACCESS-NRI/build-ci#194
The current setup for CI 2.0 is that we will have a container that contains an upstream instance of `spack` with all the compilers (and possible low-level packages) that are needed, in order to speed up build times.
This container will connect to runner (downstream) instances of `spack`, which can use the compilers without needing to build or install them.
Hence we need to demarcate the two different use-cases for `ci` - one for upstream, and one for the runners (downstream). Here are the changes:
- `config.yaml` - the install_tree for upstream will be `/opt/upstream`
- `modules.yaml` - the modules directories will be `opt/upstream/modules`/`opt/upstream/lmod`
- `upstreams.yaml` - The upstream install_tree will be found in `/opt/upstream`, which …
> Update ci spack-config for multi-container CI builds

- common/config.yaml
References ACCESS-NRI/build-cd#225
Pinging @aidanheerdegen as he helped out with this. 
Under heavy concurrent access, the spack database will lock and the installations using it will timeout after a minute. This means that if multiple of the same package needs to be installed, there is a chance that the builds will fail after a minute if the lock isn't released. 
We are increasing this timeout from 1 to 10 minutes to make this possibility less likely, pending a more robust solution in which we use a per-build containerised spack instead of one on the Gadi filesystem. 
* Increase DB lockout from 1 to 10 minutes, affecting `gadi`, `setonix`, `ci-runner` under all `v0.XX` directories, since they all symlink to this file.
> Increase `.spack-db` lock timeout from 1 to 10 mins

- common/ci-runner/concretizer.yaml
- common/ci-runner/injected.view.yaml
- v0.22/ci-runner/concretizer.yaml
- v0.22/ci-runner/injected.view.yaml
References ACCESS-NRI/build-ci#195
It seems that build-ci spack manifests should almost always use `concretizer.unify: when_possible/false` as the concretization will fail when installing multiple of the same model component packages. Instead of having to create a schema on build-ci spack manifests, we should set this configuration higher up than the environment level (namely, here!).
This only solves half the problem, though. If a view can't be created due to having the same prefix (say, installing two `mom5`s with different compilers) the installation will fail. Hence we either need to have no view (which needs to be tested), or we need to set a custom `spack.views.default.projections` section in the spack manifest. Since it's not a first order configuration file (like `config.yaml` or …
> Set `ci-runner` concretizer and view configuration in higher scope 

- common/gadi/linux/compilers.yaml
```
$ spack compiler list
==> Available compilers
-- clang rocky8-x86_64 ------------------------------------------
clang@17.0.6
-- gcc rocky8-x86_64 --------------------------------------------
gcc@8.5.0  gcc@14.1.0  gcc@13.2.0  gcc@12.2.0  gcc@11.1.0  gcc@10.3.0
-- intel rocky8-x86_64 ------------------------------------------
intel@2021.8.0  intel@2021.3.0   intel@19.1.3.304  intel@19.0.4.243
intel@2021.7.0  intel@2021.2.0   intel@19.1.2.254  intel@19.0.3.199
intel@2021.6.0  intel@2021.11.1  intel@19.1.1.217
intel@2021.5.0  intel@2021.10.0  intel@19.1.0.166
intel@2021.4.0  intel@2021.1     intel@19.0.5.281
-- oneapi rocky8-x86_64 -----------------------------------------
oneapi@2025.1.1  oneapi@2023.2.0  oneapi@2022.0.0  oneapi@2021.1
oneapi@2025.0.4  oneapi@2023.0.0  oneapi@2021.4.0 …
```
> common/gadi/linux/compilers.yaml: add new oneapi 2025.1.1 compiler

- common/gadi/linux/compilers.yaml
OneAPI 2025.2.0 is installed and available on Gadi. Add support for it in Spack.
> common/gadi/linux/compilers.yaml: add new oneapi 2025.2.0 compiler

- v1.0/all/repos.yaml
- v1.0/ci-runner/repos.yaml
- v1.0/ci-upstream/repos.yaml
- v1.0/ci/repos.yaml
- v1.0/gadi/repos.yaml
- v1.0/setonix/repos.yaml
```
[root@5596be3dc7c1 fncqgg4]# spack config blame repos
---                                          repos:
/opt/spack/etc/spack/repos.yaml:3              access.nri: $spack/../spack-packages/spack_repo/access/nri
/opt/spack/etc/spack/defaults/repos.yaml:14    builtin:
/opt/spack/etc/spack/defaults/repos.yaml:15      git: https://github.com/spack/spack-packages.git
/opt/spack/etc/spack/defaults/repos.yaml:16      branch: releases/v2025.07
[root@5596be3dc7c1 spack]# spack -V
1.0.0 (73eaea13f381e3495299284856fd02a64e1d154c)
[root@5596be3dc7c1 spack]# ls -l
total 4
lrwxrwxrwx 1 root root   45 Aug  7 07:06 concretizer.yaml -> ../../../spack-config/common/concretizer.yaml
lrwxrwxrwx 1 root root   40 Aug  7 07:06 config.yaml -> ../../../spack-config/common/config.yaml
drwxr-xr-x 6 root root …
```
> Update repos.yaml to support Spack v1.0

- common-api-v2/gadi/packages.yaml
- common/ci/packages.yaml
- common/gadi/packages.yaml
- common/setonix/packages.yaml
* Spack upstream informed us that `providers` indicates a preference, not a requirement.
* Default to `openmpi` on Gadi and CI. Default to `mpich` on Setonix.
* This can be overridden from the spack.yaml environment file.
* https://spack.readthedocs.io/en/latest/configuration.html#scope-precedence
> packages.yaml: use `require` instead of `providers` for mpi
